### ISSUE TITLE
deal with `before_chain` for PMCMC samplers

### ISSUE THREAD

**Issue by paciorek** [nimble-dev/nimbleSMC#9]
I'm getting this error in the "scalar pmcmc" test when running nimbleSMC tests with nimble version 1.0.0. I didn't think we needed to modify any of our samplers to handle the addition of `before_chain` but I must be missing something.

@danielturek can you take a look? No urgency, unless this suggests we need to modify nimble itself before release.

```
── Error (Line 36): scalar pmcmc ───────────────────────────────────────────────
Error in `envRefInferField(x, what, getClass(class(x)), selfEnv)`: ‘before_chain’ is not a valid field or method name for reference class “sampler_RW_PF”
Backtrace:
 1. global test_mcmc_internal(...)
 3. Rmcmc$run(numItsR)
 4. samplerFunctions[[i]]$before_chain
 5. methods:::envRefInferField(x, what, getClass(class(x)), selfEnv)

```

**Comment by danielturek** [comment]
@paciorek @perrydv It looks like this is something that might need to be addressed in `nimble`.  With a very quick inspection, it might be a shortcoming in the expansion of the `nimbleFunction` class inheritance system, specifically, the expansion to allow the `methodControl` argument to `nimbleFunctionVirtual`.

My very quick investigation shows:

```
library(nimble)
library(nimbleSMC)

## RW sampler from nimble package,
## class generator includes 'before_chain' and 'after_chain' methods,
## which were added automatically:
environment(sampler_RW)$nfRefClass

## RW_PF sampler from nimbleSMC package,
## class generator *does not include* 'before_chain' or 'after_chain' methods:
environment(sampler_RW_PF)$nfRefClass
```

@perrydv This raises concern that the new system for `required = FALSE` methods of a `nimbleFunctionVirtual` class, for some reason is not operating correctly for samplers defined in other packages (here, `nimbleSMC`)

**Comment by perrydv** [comment]
Hi @paciorek @danielturek.
Thanks for the clear issue. It looks to me like one simply needs to build nimbleSMC with an updated nimble that includes the version of `sampler_BASE` that includes `before_chain` and `after_chain`. I guess it is the version of `sampler_BASE` in the version of `nimble` installed when building `nimbleSMC` that determines whether the nimbleFunctions (samplers, in this case) in `nimbleSMC` include these new default methods in the base class.  When I did that, the "scalar pmcmc" test passed on my machine.

**Comment by paciorek** [comment]
Addressed inherently with upcoming release.
